name: Workflow-02 Destroy Workflow
on: 
  push:
    branches:
      - main
    paths:
      - 'Storage-Account/Delete-SA.ps1'
      - ".github/workflows/Workflow-02.yml"
  workflow_dispatch:


permissions:
  id-token: write # REQUIRED for OIDC
  contents: read        
  
jobs:
  Destroy-Resources:
    runs-on: ubuntu-24.04
    environment: 
        name: payg-swarnka-01
    env:
      ARM_USE_OIDC: true # Important: Use OIDC Auth
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    defaults:
      run:
        working-directory: ./Storage-Account/
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Files
        run: ls -ltra
 
      - name: Azure Login using OIDC
        uses: azure/login@v3
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
      
      - name: Delete Resource Group
        run: |
          az group delete \
            --name rsw-alzd-p-cin-rsg-devops \
            --yes \
            --no-wait
 